version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:${MONGO_PORT}

  neo4j:
    image: neo4j
    restart: true
    ports:
      - 7474:7474
      - 7687:7687
